            - name: Bicep Deploy
  uses: Azure/bicep-deploy@v2
  with:
    # Specifies the execution type, which can be either 'deployment' or 'deploymentStack'.
    type: 'deploymentStack'
    # Specifies the operation to perform. For deployment, choose from 'create', 'validate', 'whatIf'. For deploymentStack, choose from 'create', 'delete', 'validate'.
    operation: 'create'
    # Specifies the name of the deployment or deploymentStack.
    name: 'mydeployment'
    # Specifies the location of the deployment or deploymentStack. Must be provided if the 'scope' parameter is 'subscription', 'managementGroup' or 'tenant'.
    location: 'WestUS2'
    # Specifies the scope of the deployment or deploymentStack. For deployment, choose from 'resourceGroup', 'subscription', 'managementGroup', 'tenant'. For deploymentStack, choose from 'resourceGroup', 'subscription', 'managementGroup'.
    scope: 'resourceGroup'
    # Specifies the tenant ID.
    tenant-id: # optional
    # Specifies the management group ID.
    management-group-id: # optional
    # Specifies the subscription ID.
    subscription-id: # optional
    # Specifies the resource group name.
    resource-group-name: # optional
    # Specifies the path to the template file.
    template-file: 'main.bicep'
    # Specifies the template spec resource ID.
    template-spec: # optional
    # Specifies the HTTP URI of the template.
    template-uri: # optional
    # Specifies the path to the parameters file.
    parameters-file: # optional
    # Specifies the parameters to use.
    parameters: # optional
    # Specifies the change types to exclude from the 'What If' operation.
    what-if-exclude-change-types: # optional
    # Specifies the action to take on unmanaged resources. Choose from 'delete' or 'detach'.
    action-on-unmanage-resources: # optional
    # Specifies the action to take on unmanaged resource groups. Choose from 'delete' or 'detach'.
    action-on-unmanage-resourcegroups: # optional
    # Specifies the action to take on unmanaged management groups. Choose from 'delete' or 'detach'.
    action-on-unmanage-managementgroup: # optional
    # Specifies the mode of the deny settings. Choose from 'denyDelete', 'denyWriteAndDelete', 'none'.
    deny-settings-mode: # optional
    # Specifies the excluded actions for the deny settings.
    deny-settings-excluded-actions: # optional
    # Specifies the excluded principals for the deny settings.
    deny-settings-excluded-principals: # optional
    # When specified, the deny setting mode configuration also applies to the child scope of the managed resources.
    deny-settings-apply-to-child-scopes: # optional
    # Specifies whether to bypass the stack out of sync error. Choose from 'true' or 'false'.
    bypass-stack-out-of-sync-error: # optional
    # Specifies the description of the deploymentStack.
    description: # optional
    # Specifies the tags for the deploymentStack.
    tags: # optional
    # Specifies output names to mask values for.
    masked-outputs: # optional
    # Specifies the environment to use. Choose from 'azureCloud', 'azureChinaCloud', 'azureGermanCloud', 'azureUSGovernment'.
    environment: # optional
          
